export type ExperimentKind =
  | "Smoke test"
  | "Wizard of Oz"
  | "Concierge"
  | "Landing page"
  | "Explainer video"
  | "A/B / growth test"
  | "Viral loop"
  | "Pivot signal";

export type CompanyCase = {
  id: string;
  company: string;
  mark: string;
  sector: string;
  kind: ExperimentKind;
  theme: "desirability" | "feasibility" | "viability" | "growth";
  stage: string;
  bet: string;
  test: string;
  result: string;
  takeaway: string;
  founderMove: string;
  relatedStep: "assumptions" | "hypothesis" | "experiments" | "learnings" | "leverage";
};

/** Public, well-documented experiment stories founders can pattern-match. */
export const COMPANY_CASES: CompanyCase[] = [
  {
    id: "dropbox",
    company: "Dropbox",
    mark: "Db",
    sector: "Consumer cloud",
    kind: "Explainer video",
    theme: "desirability",
    stage: "Pre-product",
    bet: "People will want seamless file sync across computers — enough to join a waitlist before the product exists.",
    test: "Drew Houston posted a simple explainer video of the product experience (not a full multi-OS build) and a signup for early access.",
    result: "Waitlist demand exploded overnight. That signal justified building the hard engineering.",
    takeaway: "When the product is expensive to build, sell the experience first. A video can be a discovery experiment with surprisingly strong evidence of desire.",
    founderMove: "Write a hypothesis like: If we show an explainer of X, then Y% of visitors join the waitlist within Z days.",
    relatedStep: "experiments",
  },
  {
    id: "zappos",
    company: "Zappos",
    mark: "Zp",
    sector: "E-commerce",
    kind: "Wizard of Oz",
    theme: "desirability",
    stage: "Idea → first orders",
    bet: "People will buy shoes online without trying them on — if return logistics feel safe.",
    test: "Instead of building a warehouse, Nick Swinmurn photographed shoes in local stores and bought them retail when an order came in.",
    result: "Orders happened. Painful unit economics early on — but the desirability bet was proven before inventory scale.",
    takeaway: "Fake the backend. Manually fulfill. Learn if customers buy before you invest in operations.",
    founderMove: "Ask: what is the cheapest way to deliver the customer-facing promise this week?",
    relatedStep: "experiments",
  },
  {
    id: "buffer",
    company: "Buffer",
    mark: "Bf",
    sector: "SaaS / social",
    kind: "Landing page",
    theme: "viability",
    stage: "Pre-code",
    bet: "People will pay for a simpler way to schedule social posts — and a pricing page will reveal willingness to pay.",
    test: "Joel Gascoigne shipped a two-page funnel: landing → pricing. Clicking a plan led to “not ready yet” + email capture.",
    result: "Enough people tried to pay that building the product became rational. Pricing interest was evidence of viability, not just curiosity.",
    takeaway: "A “Plans” click is a stronger signal than a newsletter signup. Test money intent before features.",
    founderMove: "Hypothesis: If we show paid plans on a landing page, then ≥X% of visitors click a plan within 2 weeks.",
    relatedStep: "hypothesis",
  },
  {
    id: "airbnb",
    company: "Airbnb",
    mark: "Ab",
    sector: "Marketplace",
    kind: "A/B / growth test",
    theme: "growth",
    stage: "Early growth",
    bet: "Listing quality (photos) is the constraint holding bookings — not more features.",
    test: "In New York, the team hired photographers for host listings and compared booking rates vs. host selfies.",
    result: "Professional photos lifted bookings dramatically. Growth focused on the constraint, not the whole backlog.",
    takeaway: "This is leverage thinking: one bottleneck. Prove it with a local, reversible experiment before platform-wide spend.",
    founderMove: "Pick your top-right assumption. Run the smallest test that isolates that variable.",
    relatedStep: "leverage",
  },
  {
    id: "groupon",
    company: "Groupon",
    mark: "Gp",
    sector: "Local deals",
    kind: "Concierge",
    theme: "feasibility",
    stage: "Prototype",
    bet: "Local merchants + consumers will rally around a daily deal — even if the “platform” is duct tape.",
    test: "Early Groupon was a WordPress blog; vouchers were PDFs generated by hand when a deal tipped.",
    result: "Demand and merchant interest showed up before a scaled coupon platform existed.",
    takeaway: "Concierge / manual MVP proves the loop works. Automate after the learning, not before.",
    founderMove: "Map the customer journey. Do steps 1–3 by hand for 10 customers this week.",
    relatedStep: "experiments",
  },
  {
    id: "hotmail",
    company: "Hotmail",
    mark: "Hm",
    sector: "Email",
    kind: "Viral loop",
    theme: "growth",
    stage: "Launch growth",
    bet: "Every outbound email can recruit the next user — if the product leaves a footprint.",
    test: "They added a simple footer: “Get your free email at Hotmail” on every message users sent.",
    result: "Organic acquisition compounded. Growth became a product property, not only paid spend.",
    takeaway: "Growth hypotheses are experiments too. Instrument one loop, measure invites or signups attributable to it.",
    founderMove: "Hypothesis: If every share/email includes invite X, then Y% of recipients convert within Z days.",
    relatedStep: "hypothesis",
  },
  {
    id: "food-on-the-table",
    company: "Food on the Table",
    mark: "Ft",
    sector: "Consumer / food",
    kind: "Concierge",
    theme: "desirability",
    stage: "Customer discovery",
    bet: "Busy parents will pay for meal plans tied to local grocery deals — if the service feels personal.",
    test: "Founders interviewed parents in grocery stores, then built meal plans manually for early customers before software.",
    result: "Paying customers and retention insight arrived while the “product” was still people + spreadsheets.",
    takeaway: "Talk to customers where the pain is. Concierge service is a valid experiment design.",
    founderMove: "Run 5–10 interviews this week, then offer a manual version of the solution to three of them.",
    relatedStep: "assumptions",
  },
  {
    id: "slack",
    company: "Slack",
    mark: "Sl",
    sector: "B2B SaaS",
    kind: "Pivot signal",
    theme: "desirability",
    stage: "Pivot",
    bet: "The internal chat tool the team built for a game studio might be more valuable than the game itself.",
    test: "They treated internal usage and other companies’ interest as evidence — then killed the game and productized Slack.",
    result: "A clear learning card: evidence refuted the game bet; evidence supported the collaboration tool bet.",
    takeaway: "Persevere / pivot / kill is not failure theatre. When data points at a different constraint, move.",
    founderMove: "After every experiment, force a decision: persevere, pivot, pause, or kill — write it on a Learning Card.",
    relatedStep: "learnings",
  },
  {
    id: "superhuman",
    company: "Superhuman",
    mark: "Sh",
    sector: "Productivity SaaS",
    kind: "Landing page",
    theme: "desirability",
    stage: "PMF search",
    bet: "A premium email experience can earn very high willingness-to-pay from a narrow ICP — if “very disappointed” scores are extreme.",
    test: "They used a disciplined product-market fit survey (Sean Ellis style) plus high-touch onboarding to measure love among the right users — not vanity signups.",
    result: "Focus on the segment that would be devastated to lose the product; ignore lukewarm mass appeal early.",
    takeaway: "Precision in who you measure matters as much as what you measure. Discrete hypotheses about a segment beat “everyone will love it.”",
    founderMove: "Define the ICP in your hypothesis. Measure among them — not the whole internet.",
    relatedStep: "hypothesis",
  },
  {
    id: "pebble",
    company: "Pebble",
    mark: "Pb",
    sector: "Hardware",
    kind: "Smoke test",
    theme: "viability",
    stage: "Pre-manufacture",
    bet: "People will pre-pay for a smartwatch concept before factories spin up.",
    test: "Kickstarter as a demand + financing experiment — public pre-orders as the metric.",
    result: "Massive overfunding proved desire and willingness to commit money before inventory risk.",
    takeaway: "Hardware’s expensive. Pre-orders and crowdfunding are viability/desirability experiments with real money.",
    founderMove: "If build cost is high, design an experiment where commitment (deposit, pre-order) is the success criterion.",
    relatedStep: "experiments",
  },
];

export const CASE_KINDS = [
  "All",
  "Explainer video",
  "Wizard of Oz",
  "Concierge",
  "Landing page",
  "Smoke test",
  "A/B / growth test",
  "Viral loop",
  "Pivot signal",
] as const;

export function casesForStep(step: CompanyCase["relatedStep"]) {
  return COMPANY_CASES.filter((c) => c.relatedStep === step);
}

export function casesForKind(kind: string) {
  if (kind === "All") return COMPANY_CASES;
  return COMPANY_CASES.filter((c) => c.kind === kind);
}
